Scrape data command
maxdg99/sei-website pull request #33
Opened 2022-02-08 15:39 UTC by maxdg99

- Integrates all of our scraping efforts into one scrape command: `python manage.py scrape`.
- Moves over to a name.# schema for instructor ID

2022-02-09 01:31 UTC, adambricelis requested changes
Nice work! Thanks for deleting all of those files we don't need anymore.

2022-02-09 01:31 UTC, adambricelis commented on sei_website/sei_website_app/management/scrape/scrape_post_2018.py
> +USER_ID = "tzIsE9d1Yhs1zr3yqg4mmuJGbBZUgIuxAwZgaTk7ktRmJZNFp8naKp"
We should put this in the .env file

2022-02-09 01:31 UTC, adambricelis commented on README.md
> +## Scraping Data
If we add USER_ID to the .env file, we need to add that to these instructions

2022-02-10 16:42 UTC, maxdg99 commented on README.md
> +## Scraping Data
Done

2022-02-10 16:43 UTC, maxdg99 commented on sei_website/sei_website_app/management/scrape/scrape_post_2018.py
> +USER_ID = "tzIsE9d1Yhs1zr3yqg4mmuJGbBZUgIuxAwZgaTk7ktRmJZNFp8naKp"
Done

2022-02-10 18:07 UTC, merged